version: "3"
 
services:
    brainly_web:
        image: 443736785131.dkr.ecr.ap-southeast-1.amazonaws.com/brainly_web
        build: ./web
        ports:
            - '80:80'
        command: 'bash start-env.sh'
        deploy:
          resources:
            limits:
              cpus: '1'
              memory: 2048M

    brainly_api:
        image: 443736785131.dkr.ecr.ap-southeast-1.amazonaws.com/brainly_api
        build: ./api
        ports:
            - '3000:3000'
        environment:
            - DB_HOST=brainly_mysql
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_NAME=mydb
        command: "bash start.sh brainly_mysql:3306 brainly_redis:6379"
    
    brainly_mysql:
        image: mysql:5.7.32
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=mydb
    
    brainly_redis:
        image: redis
        ports:
            - "6379:6379"
        command: 'redis-server --requirepass "Password123"'